#!/bin/bash
dir="$(pwd)"
parentdir="$(dirname "$dir")"
echo $dir
echo $parentdir
cd ..
ls
echo "$(pwd)"
docker run --user root --rm -v "$(pwd)":/home/gradle/project -w /home/gradle/project gradle:4.8.1 gradle clean build
